apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 very bad problem
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: payment
        image: nginx
        resources: 
          limits: 
            cpu: 200            
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE

#containers[] .resources .limits .cpu